version: '3.4'

services:
  ctf_game:
    image: ${DOCKER_REGISTRY-}ctfgame
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - 8081:8098
    networks:
      game:
        ipv4_address: 10.5.0.10
  frontend:
    build:
      context: "Web/client/"
      dockerfile: "Dockerfile"
    ports:
    - 8080:8080
    networks:
      game:
        ipv4_address: 10.5.0.9

networks:
  game:
    driver: bridge
    ipam:
      config:
       - subnet: 10.5.0.0/16